In [1]:
import pandas as pd

In [2]:
#Loading all the csv files and assigning them to variables
# Cross walk of County, Commuting Zone and State
cb = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\cty_cz_st_crosswalk.csv', index_col = None)
cb.head()

    cty county_name     cz     cz_name statename  state_fips stateabbrv
0  1001     Autauga  11101  Montgomery   Alabama           1         AL
1  1003     Baldwin  11001      Mobile   Alabama           1         AL
2  1005     Barbour  10301     Eufaula   Alabama           1         AL
3  1007        Bibb  10801  Tuscaloosa   Alabama           1         AL
4  1009      Blount  10700  Birmingham   Alabama           1         AL

In [3]:
# National life expectancy estimates (pooling 2001-14) for men and women, by income percentile 
table1 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_1.csv', index_col = None)

# National by-year life expectancy estimates for men and women, by income percentile
table2 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_2.csv', index_col = None)

# State-level life expectancy estimates for men and women, by income quartile
table3 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_3.csv', index_col = None)

# State-level estimates of trends in life expectancy for men and women, by income quartile
table4 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_4.csv', index_col = None)

# State-level by-year life expectancy estimates for men and women, by income quartile 
table5 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_5.csv', index_col = None)

# CZ-level life expectancy estimates for men and women, by income quartile
table6 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_6.csv', index_col = None)

# CZ-level life expectancy estimates for men and women, by income ventile
table7 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_7.csv', index_col = None)

# CZ-level estimates of trends in life expectancy for men and women, by income quartile
table8 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_8.csv', index_col = None)

# CZ-level by-year life expectancy estimates for men and women, by income quartile
table9 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_9.csv', index_col = None)

# CZ-level characteristics described in eTable 9
table10 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_10.csv', index_col = None)

# County-level life expectancy estimates for men and women, by income quartile
table11 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_11.csv', index_col = None)

# County-level characteristics described in eTable 9
# table 12 was not reading. Found out by commenting out every line. Added a parameter of pd.read_csv 'encoding = latin-1' to make it work
table12 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_12.csv', index_col = None, encoding = 'latin-1')

# International estimates of mean life expectancy at age 40, by country for men and women
table13 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_13.csv', index_col = None)

# Comparison of population and death counts in tax data and NCHS data 
table14 = pd.read_csv(r'C:\Users\ROBI\OneDrive\ডেস্কটপ\Springboard_2021\Capstone-02\1. Data-Set\health_ineq_online_table_14.csv', index_col = None)